// packages/ui/src/svelte/components/CopyButton.svelte
<script>
  export let text = ''
  export let label = 'Copy'

  let copied = false

  async function handleCopy() {
    if (!text) return
    await navigator.clipboard.writeText(text)
    copied = true
    setTimeout(() => {
      copied = false
    }, 1200)
  }
</script>

<button type="button" class="copy-button" on:click={handleCopy}>
  {copied ? 'Copied' : label}
</button>

<style>
  .copy-button {
    border: 1px solid var(--relay-surface-border);
    border-radius: 999px;
    background: transparent;
    color: var(--relay-muted);
    padding: 0.28rem 0.7rem;
    font: 700 0.6563rem/1 var(--relay-font-mono);
    text-transform: uppercase;
    letter-spacing: 0.06em;
    cursor: pointer;
    transition: color 150ms ease, border-color 150ms ease;
  }

  .copy-button:hover {
    color: var(--relay-text);
    border-color: var(--relay-cyan);
  }
</style>

// packages/ui/src/react/components/CopyButton.tsx
import React, { useEffect, useRef, useState } from 'react'

export interface CopyButtonProps {
  text: string
  label?: string
}

// The React build styles inline rather than with classes, so this mirrors the
// Svelte button's look through the React theme variables instead of its CSS.
const copyButtonStyle: React.CSSProperties = {
  borderRadius: '999px',
  border: '1px solid var(--rb-border)',
  background: 'transparent',
  color: 'var(--rb-muted)',
  padding: '0.28rem 0.7rem',
  fontFamily: 'var(--rb-font-mono, monospace)',
  fontSize: '0.6563rem',
  fontWeight: 700,
  lineHeight: 1,
  textTransform: 'uppercase',
  letterSpacing: '0.06em',
  cursor: 'pointer',
  flexShrink: 0,
}

/**
 * React counterpart of svelte/components/CopyButton.svelte, down to the 1200 ms
 * "Copied" window, so the same deployment card reads the same in both builds.
 */
export function CopyButton({ text, label = 'Copy' }: CopyButtonProps) {
  const [copied, setCopied] = useState(false)
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(
    () => () => {
      if (timer.current) clearTimeout(timer.current)
    },
    [],
  )

  const handleCopy = async () => {
    if (!text) return
    await navigator.clipboard.writeText(text)
    setCopied(true)
    if (timer.current) clearTimeout(timer.current)
    timer.current = setTimeout(() => setCopied(false), 1200)
  }

  return (
    <button type="button" style={copyButtonStyle} onClick={() => void handleCopy()}>
      {copied ? 'Copied' : label}
    </button>
  )
}

export default CopyButton
